module Lcms
  module Engine
    FLASH_MESSAGE_MAX_CHAR: Integer
    FLASH_REDIS_PREFIX: ::String

    def self.table_name_prefix: -> ::String

    class Engine < ::Rails::Engine
      def self.config: -> untyped
      def self.initializer: (*untyped?) ?{ (untyped?) -> untyped } -> untyped
      def self.root: -> untyped
      def self.routes: -> ActionDispatch::Routing::RouteSet
    end
  end
end
