verify_signatures: false

PreCommit:
  RuboCop:
    command: ['rubocop', '--force-exclusion']
    enabled: true
    on_warn: fail
    exclude:
      - bin/*
      - db/migrate/*
      - spec/dummy/**/*

  BundleCheck:
    enabled: true

  BundleOutdated:
    enabled: true

  LocalPathsInGemfile:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
    - bin/*
    - spec/dummy/bin/*
    - .codeship/*

  YamlSyntax:
    enabled: true

  CustomScript:
    enabled: true
    description: Js/Scss linters
    command: ['yarn', 'lint']

  TrailingWhitespace:
    enabled: true

PostCheckout:
  ALL:
    quiet: true # Change all post-checkout hooks to only display output on failure

  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes

PrePush:
  RSpec:
    enabled: true
