AllCops:
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - spec/dummy/db/schema.rb
    - spec/dummy/bin/*
    - templates/*
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 39

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'config/routes.rb'
    - 'lcms-engine.gemspec'
    - 'lib/tasks/elasticsearch.rake'
  ExcludedMethods: ['guard', 'included', 'class_eval']

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 10

Naming/MethodParameterName:
  MinNameLength: 2

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%r': '{}'
    '%w': '()'

Style/RescueModifier:
  Enabled: false
