module DocTemplate
  module Objects
    class ActivityMetadata
      include Virtus::InstanceMethods::Constructor
      extend Virtus::InstanceMethods::_Constructor
      extend _TocHelpers
      include TocHelpers

      class Activity
        include Virtus::InstanceMethods::Constructor
        extend Virtus::InstanceMethods::_Constructor

        include MetadataHelpers
      end

      def self.build_from: (untyped data) -> untyped
    end
  end
end
