module DocTemplate
  module Objects
    class ActivityMetadata
      include DocTemplate::Objects::TocHelpers

      class Activity
        include DocTemplate::Objects::MetadataHelpers

        def activity_standard_info: () -> untyped
      end

      def self.build_from: (untyped data) -> untyped
    end
  end
end
