module DocTemplate
  module Objects
    module MetadataHelpers
      SEPARATOR: ::Regexp

      def self.build_anchor_from: (untyped item) -> untyped

      def standard_info: (untyped standards) -> untyped
    end
  end
end
