module Lcms
  module Engine
    class ResourceAdditionalResource < ::Lcms::Engine::ApplicationRecord
      extend _ActiveRecord_Relation_ClassMethods[Lcms::Engine::ResourceAdditionalResource, ActiveRecord_Relation, Integer]

      module GeneratedAttributeMethods
        def id: () -> Integer

        def id=: (Integer) -> Integer

        def id?: () -> bool

        def id_changed?: () -> bool

        def id_change: () -> [ Integer?, Integer? ]

        def id_will_change!: () -> void

        def id_was: () -> Integer?

        def id_previously_changed?: () -> bool

        def id_previous_change: () -> Array[Integer?]?

        def id_previously_was: () -> Integer?

        def id_before_last_save: () -> Integer?

        def id_change_to_be_saved: () -> Array[Integer?]?

        def id_in_database: () -> Integer?

        def saved_change_to_id: () -> Array[Integer?]?

        def saved_change_to_id?: () -> bool

        def will_save_change_to_id?: () -> bool

        def restore_id!: () -> void

        def clear_id_change: () -> void

        def resource_id: () -> Integer

        def resource_id=: (Integer) -> Integer

        def resource_id?: () -> bool

        def resource_id_changed?: () -> bool

        def resource_id_change: () -> [ Integer?, Integer? ]

        def resource_id_will_change!: () -> void

        def resource_id_was: () -> Integer?

        def resource_id_previously_changed?: () -> bool

        def resource_id_previous_change: () -> Array[Integer?]?

        def resource_id_previously_was: () -> Integer?

        def resource_id_before_last_save: () -> Integer?

        def resource_id_change_to_be_saved: () -> Array[Integer?]?

        def resource_id_in_database: () -> Integer?

        def saved_change_to_resource_id: () -> Array[Integer?]?

        def saved_change_to_resource_id?: () -> bool

        def will_save_change_to_resource_id?: () -> bool

        def restore_resource_id!: () -> void

        def clear_resource_id_change: () -> void

        def additional_resource_id: () -> Integer

        def additional_resource_id=: (Integer) -> Integer

        def additional_resource_id?: () -> bool

        def additional_resource_id_changed?: () -> bool

        def additional_resource_id_change: () -> [ Integer?, Integer? ]

        def additional_resource_id_will_change!: () -> void

        def additional_resource_id_was: () -> Integer?

        def additional_resource_id_previously_changed?: () -> bool

        def additional_resource_id_previous_change: () -> Array[Integer?]?

        def additional_resource_id_previously_was: () -> Integer?

        def additional_resource_id_before_last_save: () -> Integer?

        def additional_resource_id_change_to_be_saved: () -> Array[Integer?]?

        def additional_resource_id_in_database: () -> Integer?

        def saved_change_to_additional_resource_id: () -> Array[Integer?]?

        def saved_change_to_additional_resource_id?: () -> bool

        def will_save_change_to_additional_resource_id?: () -> bool

        def restore_additional_resource_id!: () -> void

        def clear_additional_resource_id_change: () -> void

        def position: () -> Integer?

        def position=: (Integer?) -> Integer?

        def position?: () -> bool

        def position_changed?: () -> bool

        def position_change: () -> [ Integer?, Integer? ]

        def position_will_change!: () -> void

        def position_was: () -> Integer?

        def position_previously_changed?: () -> bool

        def position_previous_change: () -> Array[Integer?]?

        def position_previously_was: () -> Integer?

        def position_before_last_save: () -> Integer?

        def position_change_to_be_saved: () -> Array[Integer?]?

        def position_in_database: () -> Integer?

        def saved_change_to_position: () -> Array[Integer?]?

        def saved_change_to_position?: () -> bool

        def will_save_change_to_position?: () -> bool

        def restore_position!: () -> void

        def clear_position_change: () -> void

        def created_at: () -> ActiveSupport::TimeWithZone

        def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

        def created_at?: () -> bool

        def created_at_changed?: () -> bool

        def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

        def created_at_will_change!: () -> void

        def created_at_was: () -> ActiveSupport::TimeWithZone?

        def created_at_previously_changed?: () -> bool

        def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

        def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

        def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

        def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

        def created_at_in_database: () -> ActiveSupport::TimeWithZone?

        def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

        def saved_change_to_created_at?: () -> bool

        def will_save_change_to_created_at?: () -> bool

        def restore_created_at!: () -> void

        def clear_created_at_change: () -> void

        def updated_at: () -> ActiveSupport::TimeWithZone

        def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

        def updated_at?: () -> bool

        def updated_at_changed?: () -> bool

        def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

        def updated_at_will_change!: () -> void

        def updated_at_was: () -> ActiveSupport::TimeWithZone?

        def updated_at_previously_changed?: () -> bool

        def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

        def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

        def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

        def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

        def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

        def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

        def saved_change_to_updated_at?: () -> bool

        def will_save_change_to_updated_at?: () -> bool

        def restore_updated_at!: () -> void

        def clear_updated_at_change: () -> void
      end
      include GeneratedAttributeMethods

      def resource: () -> Lcms::Engine::Resource
      def resource=: (Lcms::Engine::Resource?) -> Lcms::Engine::Resource?
      def reload_resource: () -> Lcms::Engine::Resource?
      def build_resource: (untyped) -> Lcms::Engine::Resource
      def create_resource: (untyped) -> Lcms::Engine::Resource
      def create_resource!: (untyped) -> Lcms::Engine::Resource
      def additional_resource: () -> Lcms::Engine::Resource
      def additional_resource=: (Lcms::Engine::Resource?) -> Lcms::Engine::Resource?
      def reload_additional_resource: () -> Lcms::Engine::Resource?
      def build_additional_resource: (untyped) -> Lcms::Engine::Resource
      def create_additional_resource: (untyped) -> Lcms::Engine::Resource
      def create_additional_resource!: (untyped) -> Lcms::Engine::Resource
      module GeneratedAssociationMethods
      end
      include GeneratedAssociationMethods

      module GeneratedRelationMethods
      end

      class ActiveRecord_Relation < ::ActiveRecord::Relation
        include GeneratedRelationMethods
        include _ActiveRecord_Relation[Lcms::Engine::ResourceAdditionalResource, Integer]
        include Enumerable[Lcms::Engine::ResourceAdditionalResource]
      end

      class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
        include GeneratedRelationMethods
        include _ActiveRecord_Relation[Lcms::Engine::ResourceAdditionalResource, Integer]
      end
    end
  end
end
