module Lcms
  module Engine
    module Generators
      class InstallGenerator < Rails::Generators::Base
        def copy_config_files: -> untyped

        def directory: (*untyped?) -> untyped

        def update_gemfile: -> untyped
      end
    end
  end
end
