module DocTemplate
  module Tables
    class Base
      module ChildrenConstants
        HEADER_LABEL: String
        HTML_VALUE_FIELDS: Array[String]
      end
      include ChildrenConstants

      SPLIT_REGEX: ::Regexp

      attr_reader errors: untyped

      attr_reader data: untyped

      def self.parse: (untyped fragment, *untyped) -> untyped
      def self.flatten_table: (untyped table) -> untyped

      def initialize: () -> void
      def collect_and_render_tags: (untyped data, untyped fields, ?::Hash[untyped, untyped] opts) -> untyped
      def parse: (untyped fragment, *untyped args) -> self
      def parse_in_context: (untyped content, ?::Hash[untyped, untyped] opts) -> untyped
      def fetch_materials: (untyped data, untyped key) -> untyped
      def table_exist?: () -> untyped

      attr_reader options: untyped
      attr_reader table_exists: untyped

      def fetch: (untyped table) -> untyped
      def xpath_meta_headers: () -> ::String
    end
  end
end
