module DocTemplate
  module Tags
    module Helpers
      include ActionView::Helpers::TagHelper

      TAG_NAME: String

      def materials_container: (untyped props) -> (nil | untyped)

      def priority_description: (untyped activity) -> (nil | untyped)
    end
  end
end
