ignore_unreachable_actions:
  - ^ckeditor
  - ^devise
  - ^foundation
  - lcms_engine
  - rails_info
  - rails_mailers
ignore_unused_routes:
  - ^lcms/engine/admin/access_codes#edit # accessed via `edit_admin_access_code_path`
  - ^lcms/engine/admin\/reading_assignment_texts # accessed via `association_picker_field` helper
  - ^devise
  - ^lcms/engine/pages#forthcoming # Used by `LinkTag`
