module DocTemplate
  module Objects
    class SectionsMetadata
      include Virtus::InstanceMethods::Constructor
      extend Virtus::InstanceMethods::_Constructor
      include TocHelpers
      extend _TocHelpers

      class Section
        include Virtus::InstanceMethods::Constructor
        extend Virtus::InstanceMethods::_Constructor

        def add_activity: (untyped activity) -> untyped

        def children: -> Array[ActivityMetadata::Activity]

        def handled: -> Virtus::Attribute::Boolean

        def time: -> Integer
        def time=: (Integer)-> Integer
      end

      def self.build_from: (untyped data) -> untyped

      def add_break: () -> untyped

      def children: -> Array[Section]
    end
  end
end
