module Lt
  module Lcms
    module Metadata
      class Service < BaseService
        def self.agenda: () -> untyped

        def self.materials_metadata: () -> untyped

        def self.options_for: (untyped context) -> untyped

        def self.parse: (untyped content, *untyped args) -> self

        private

        def self.lesson_options: () -> { activity: untyped, agenda: untyped, sections: untyped }

        def self.target_table?: () -> (false | untyped)
      end
    end
  end
end
