module Lcms
  module Engine
    class Document < ApplicationRecord
      include Filterable

      include Partable

      GOOGLE_URL_PREFIX: "https://docs.google.com/document/d"

      def activate!: () -> untyped

      def assessment?: () -> untyped

      def ela?: () -> untyped

      def file_url: () -> (nil | ::String)

      def gdoc_material_ids: () -> untyped

      def materials_anchors: () -> untyped

      def math?: () -> untyped

      def ordered_material_ids: () -> untyped

      def tmp_link: (untyped key) -> untyped

      private

      def clean_curriculum_metadata: () -> (nil | untyped)

      def set_resource_from_metadata: () -> (nil | untyped)
    end
  end
end
