module Lcms
  module Engine
    class Material < ApplicationRecord
      include PgSearch::Model

      include Partable

      def self.where_metadata_any_of: (untyped conditions) -> untyped

      def file_url: () -> ::String

      # Material is optional if it's included in optional activity only
      def optional_for?: (untyped document) -> untyped

      def pdf?: () -> untyped

      def source_type: () -> ("pdf" | "gdoc")
    end
  end
end
