module Lcms
  module Engine
    class User < ApplicationRecord
      def generate_password: () -> untyped

      private

      def access_code_valid?: () -> (nil | untyped)

      # NOTE: temporary disable confirmable due to issues with server setup
      def confirmation_required?: () -> false
    end
  end
end
