module DocTemplate
  module Tags
    class LanguageArtsObjectivesTag < BlockTag
      TAG_NAME: "language arts objectives"

      TEMPLATE: "language_arts_objectives.html.erb"

      def parse: (untyped node, ?::Hash[untyped, untyped] opts) -> self
    end
  end
end
