module DocTemplate
  module Tags
    class OptBreakTag < BaseTag
      TAG_NAME: "optbreak"

      TEMPLATES: { default: "opt_break.html.erb", gdoc: "gdoc/opt_break.html.erb" }

      def parse: (untyped node, ?::Hash[untyped, untyped] opts) -> self
    end
  end
end
